from copy import deepcopy


SUPPORTED_BRACKET_SIZES = (4, 8)


BRACKET_TEMPLATES = {
    4: [
        {
            "id": "UB1",
            "title": "Rodada 1 Superior - Confronto 1",
            "stage": "Rodada 1 Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "team", "index": 0},
            "slot2": {"kind": "team", "index": 3},
        },
        {
            "id": "UB2",
            "title": "Rodada 1 Superior - Confronto 2",
            "stage": "Rodada 1 Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "team", "index": 1},
            "slot2": {"kind": "team", "index": 2},
        },
        {
            "id": "UBF",
            "title": "Final Superior",
            "stage": "Final Superior",
            "bracket": "Upper",
            "best_of": "MD3",
            "slot1": {"kind": "winner", "match": "UB1"},
            "slot2": {"kind": "winner", "match": "UB2"},
        },
        {
            "id": "LB1",
            "title": "Rodada 1 Inferior",
            "stage": "Rodada 1 Inferior",
            "bracket": "Lower",
            "best_of": "MD1",
            "slot1": {"kind": "loser", "match": "UB1"},
            "slot2": {"kind": "loser", "match": "UB2"},
        },
        {
            "id": "LBF",
            "title": "Final Inferior",
            "stage": "Final Inferior",
            "bracket": "Lower",
            "best_of": "MD3",
            "slot1": {"kind": "winner", "match": "LB1"},
            "slot2": {"kind": "loser", "match": "UBF"},
        },
        {
            "id": "GF",
            "title": "Grande Final",
            "stage": "Grande Final",
            "bracket": "Final",
            "best_of": "MD5",
            "slot1": {"kind": "winner", "match": "UBF"},
            "slot2": {"kind": "winner", "match": "LBF"},
        },
    ],
    8: [
        {
            "id": "UB1",
            "title": "Rodada 1 Superior - Confronto 1",
            "stage": "Rodada 1 Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "team", "index": 0},
            "slot2": {"kind": "team", "index": 7},
        },
        {
            "id": "UB2",
            "title": "Rodada 1 Superior - Confronto 2",
            "stage": "Rodada 1 Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "team", "index": 3},
            "slot2": {"kind": "team", "index": 4},
        },
        {
            "id": "UB3",
            "title": "Rodada 1 Superior - Confronto 3",
            "stage": "Rodada 1 Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "team", "index": 1},
            "slot2": {"kind": "team", "index": 6},
        },
        {
            "id": "UB4",
            "title": "Rodada 1 Superior - Confronto 4",
            "stage": "Rodada 1 Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "team", "index": 2},
            "slot2": {"kind": "team", "index": 5},
        },
        {
            "id": "UB5",
            "title": "Semifinal Superior - Confronto 1",
            "stage": "Semifinal Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "winner", "match": "UB1"},
            "slot2": {"kind": "winner", "match": "UB2"},
        },
        {
            "id": "UB6",
            "title": "Semifinal Superior - Confronto 2",
            "stage": "Semifinal Superior",
            "bracket": "Upper",
            "best_of": "MD1",
            "slot1": {"kind": "winner", "match": "UB3"},
            "slot2": {"kind": "winner", "match": "UB4"},
        },
        {
            "id": "UBF",
            "title": "Final Superior",
            "stage": "Final Superior",
            "bracket": "Upper",
            "best_of": "MD3",
            "slot1": {"kind": "winner", "match": "UB5"},
            "slot2": {"kind": "winner", "match": "UB6"},
        },
        {
            "id": "LB1",
            "title": "Rodada 1 Inferior - Confronto 1",
            "stage": "Rodada 1 Inferior",
            "bracket": "Lower",
            "best_of": "MD1",
            "slot1": {"kind": "loser", "match": "UB1"},
            "slot2": {"kind": "loser", "match": "UB2"},
        },
        {
            "id": "LB2",
            "title": "Rodada 1 Inferior - Confronto 2",
            "stage": "Rodada 1 Inferior",
            "bracket": "Lower",
            "best_of": "MD1",
            "slot1": {"kind": "loser", "match": "UB3"},
            "slot2": {"kind": "loser", "match": "UB4"},
        },
        {
            "id": "LB3",
            "title": "Rodada 2 Inferior - Confronto 1",
            "stage": "Rodada 2 Inferior",
            "bracket": "Lower",
            "best_of": "MD1",
            "slot1": {"kind": "winner", "match": "LB1"},
            "slot2": {"kind": "loser", "match": "UB5"},
        },
        {
            "id": "LB4",
            "title": "Rodada 2 Inferior - Confronto 2",
            "stage": "Rodada 2 Inferior",
            "bracket": "Lower",
            "best_of": "MD1",
            "slot1": {"kind": "winner", "match": "LB2"},
            "slot2": {"kind": "loser", "match": "UB6"},
        },
        {
            "id": "LB5",
            "title": "Semifinal Inferior",
            "stage": "Semifinal Inferior",
            "bracket": "Lower",
            "best_of": "MD1",
            "slot1": {"kind": "winner", "match": "LB3"},
            "slot2": {"kind": "winner", "match": "LB4"},
        },
        {
            "id": "LBF",
            "title": "Final Inferior",
            "stage": "Final Inferior",
            "bracket": "Lower",
            "best_of": "MD3",
            "slot1": {"kind": "winner", "match": "LB5"},
            "slot2": {"kind": "loser", "match": "UBF"},
        },
        {
            "id": "GF",
            "title": "Grande Final",
            "stage": "Grande Final",
            "bracket": "Final",
            "best_of": "MD5",
            "slot1": {"kind": "winner", "match": "UBF"},
            "slot2": {"kind": "winner", "match": "LBF"},
        },
    ],
}


def default_state() -> dict:
    return {
        "cards_pool": [],
        "drawn_cards": [],
        "players_pool": [],
        "team_count": 4,
        "generated_teams": [],
        "team_profiles": [],
        "registered_teams": [],
        "bracket_size": 4,
        "match_results": {},
        "match_schedule": {},
        "selected_match_id": "",
        "api_settings": {},
        "player_validation_cache": {},
        "team_draw": {
            "draw_order": [],
            "current_pair": [],
            "is_finalized": False,
        },
        "map_pool": [],
        "map_draft": {
            "team_one_slot": 0,
            "team_two_slot": 1,
            "series_type": "MD3",
            "actions": [],
        },
    }


def get_bracket_template(size: int) -> list[dict]:
    if size not in BRACKET_TEMPLATES:
        raise ValueError(f"Bracket size not supported: {size}")
    return deepcopy(BRACKET_TEMPLATES[size])